#include <stdio.h>
#include "ft_printf.h"
#include <limits.h>

int main(void)
{
  char c = 'a';
  int x = 0;
  int *p = &x;
  int nbr = -2147483647;
  unsigned int unbr = 4294967295;
  char *str = "You Shall Not Pass";
  char *s2 = "Mussum Ipsum, cacilds vidis litro abertis. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. Atirei o pau no gatis, per gatis num morreus.";

  ft_printf("1 my function testing c format = %c \n", c);
  printf("real printf value = %c \n\n\n", c);
  ft_printf("2 my function testing s format = %s \n", str);
  printf("real printf value = %s \n\n\n", str);
  ft_printf("3 my function testing d format = %d \n", nbr);
  printf("real printf value = %d \n\n\n", nbr);
  ft_printf("4 my function testing i format = %i \n", nbr);
  printf("real printf value = %i \n\n\n", nbr);
  ft_printf("5 my function testing u format = %u \n", unbr);
  printf("real printf value = %u \n\n\n", unbr);
  ft_printf("6 my function testing x format = %x \n", x);
  printf("real printf value = %x \n\n\n", x);
  ft_printf("7 my function testing X format = %X \n", x);
  printf("real printf value = %X \n\n\n", x);
  ft_printf("8 my function testing p format = %p \n", p);
  printf("real printf value = %p \n\n\n\n", p);  
  
  ft_printf("THIS IS THE C TESTING FORMAT \n\n");
  ft_printf("1- %c \n", '0');
  printf("1- %c \n\n", '0');
  ft_printf("2- %c \n", '0' - 256);
  printf("2- %c \n\n", '0' - 256);
  ft_printf("3-%c \n", '0' + 256);
  printf("3-%c \n\n", '0' + 256);
  ft_printf("4- %c %c %c \n", '0', 0, '1');
  printf("4- %c %c %c \n\n", '0', 0, '1');
  ft_printf("5- %c %c %c \n", ' ', ' ', ' ');
  printf("5- %c %c %c \n\n", ' ', ' ', ' ');
  ft_printf("6- %c %c %c \n", '1', '2', '3');
  printf("6- %c %c %c \n\n", '1', '2', '3');
  ft_printf("7- %c %c %c \n", '2', '1', 0);
  printf("7- %c %c %c \n\n", '2', '1', 0);
  ft_printf("8- %c %c %c \n", 0, '1', '2');
  printf("8- %c %c %c \n\n", 0, '1', '2');

  ft_printf("THIS IS THE S TESTING FORMAT \n\n");
  ft_printf(" %s\n", "");
  printf(" %s\n", "");
  ft_printf("%s \n", "");
  printf("%s \n", "");
  ft_printf(" %s \n", "");
  printf(" %s \n", "");
  ft_printf(" %s \n", "-");
  printf(" %s \n", "-");
  ft_printf(" %s %s \n", "\n", "-");
  printf(" %s %s \n", "\n", "-");
  ft_printf(" %s %s \n", " - \n", "");
  printf(" %s %s \n", " - \n", "");
  ft_printf(" %s %s %s %s %s\n", " - ", "", "4", "", s2);
  printf(" %s %s %s %s %s\n", " - ", "", "4", "", s2);
  ft_printf(" %s %s %s %s %s \n", " - ", "", "4", "", "2 ");
  printf(" %s %s %s %s %s \n", " - ", "", "4", "", "2 ");
  ft_printf(" NULL %s NULL \n", NULL);
  printf(" NULL %s NULL \n", NULL);

  ft_printf("THIS IS THE P TESTING FORMAT \n\n");
  ft_printf(" %p \n", -1);
  printf(" %p \n", -1);
  ft_printf(" %p \n", 1);
  printf(" %p \n", 1);
  ft_printf(" %p \n", 15);
  printf(" %p \n", 15);
  ft_printf(" %p \n", 16);
  printf(" %p \n", 16);
  ft_printf(" %p \n", 17);
  printf(" %p \n", 17);
  ft_printf(" %p %p \n", LONG_MIN, LONG_MAX);
  printf(" %p %p \n", LONG_MIN, LONG_MAX); 
  ft_printf(" %p %p \n", INT_MIN, INT_MAX);
  printf(" %p %p \n", INT_MIN, INT_MAX);
  ft_printf(" %p %p \n", ULONG_MAX, -ULONG_MAX);
  printf(" %p %p \n", ULONG_MAX, -ULONG_MAX);
  ft_printf(" %p %p \n", 0, 0);
  printf(" %p %p \n", 0, 0);
  
  ft_printf("THIS IS THE D TESTING FORMAT \n\n");
  ft_printf(" %d \n", 0);
  printf(" %d \n", 0);
  ft_printf(" %d \n", -1);
  printf(" %d \n", -1);
  ft_printf(" %d \n", 1);
  printf(" %d \n", 1);
  ft_printf(" %d \n", 9);
  printf(" %d \n", 9);
  ft_printf(" %d \n", 10);
  printf(" %d \n", 10);
  ft_printf(" %d \n", 11);
  printf(" %d \n", 11);
  ft_printf(" %d \n", 15);
  printf(" %d \n", 15);
  ft_printf(" %d \n", 16);
  printf(" %d \n", 16);
  ft_printf(" %d \n", 17);
  printf(" %d \n", 17);
  ft_printf(" %d \n", 99);
  printf(" %d \n", 99);
  ft_printf(" %d \n", 100);
  printf(" %d \n", 100);
  ft_printf(" %d \n", 101);
  printf(" %d \n", 101);
  ft_printf(" %d \n", -9);
  printf(" %d \n", -9);
  ft_printf(" %d \n", -10);
  printf(" %d \n", -10);
  ft_printf(" %d \n", -11);
  printf(" %d \n", -11);
  ft_printf(" %d \n", -14);
  printf(" %d \n", -14);
  ft_printf(" %d \n", -15);
  printf(" %d \n", -15);
  ft_printf(" %d \n", -16);
  printf(" %d \n", -16);
  ft_printf(" %d \n", -99);
  printf(" %d \n", -99);
  ft_printf(" %d \n", -100);
  printf(" %d \n", -100);
  ft_printf(" %d \n", -101);
  printf(" %d \n", -101);
  ft_printf(" %d \n", INT_MAX);
  printf(" %d \n", INT_MAX);
  ft_printf(" %d \n", INT_MIN);
  printf(" %d \n", INT_MIN);
  ft_printf(" %d \n", LONG_MAX);
  printf(" %d \n", LONG_MAX);
  ft_printf(" %d \n", LONG_MIN);
  printf(" %d \n", LONG_MIN);
  ft_printf(" %d \n", UINT_MAX);
  printf(" %d \n", UINT_MAX);
  ft_printf(" %d \n", ULONG_MAX);
  printf(" %d \n", ULONG_MAX);
  ft_printf(" %d \n", 9223372036854775807LL);
  printf(" %d \n", 9223372036854775807LL);
  ft_printf(" %d %d %d %d %d %d %d\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
  printf(" %d %d %d %d %d %d %d\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
  
  ft_printf("THIS IS THE I TESTING FORMAT \n\n");
  ft_printf(" %i \n", 0);
  printf(" %i \n", 0);
  ft_printf(" %i \n", -1);
  printf(" %i \n", -1);
  ft_printf(" %i \n", 1);
  printf(" %i \n", 1);
  ft_printf(" %i \n", 9);
  printf(" %i \n", 9);
  ft_printf(" %i \n", 10);
  printf(" %i \n", 10);
  ft_printf(" %i \n", 11);
  printf(" %i \n", 11);
  ft_printf(" %i \n", 15);
  printf(" %i \n", 15);
  ft_printf(" %i \n", 16);
  printf(" %i \n", 16);
  ft_printf(" %i \n", 17);
  printf(" %i \n", 17);
  ft_printf(" %i \n", 99);
  printf(" %i \n", 99);
  ft_printf(" %i \n", 100);
  printf(" %i \n", 100);
  ft_printf(" %i \n", 101);
  printf(" %i \n", 101);
  ft_printf(" %i \n", -9);
  printf(" %i \n", -9);
  ft_printf(" %i \n", -10);
  printf(" %i \n", -10);
  ft_printf(" %i \n", -11);
  printf(" %i \n", -11);
  ft_printf(" %i \n", -14);
  printf(" %i \n", -14);
  ft_printf(" %i \n", -15);
  printf(" %i \n", -15);
  ft_printf(" %i \n", -16);
  printf(" %i \n", -16);
  ft_printf(" %i \n", -99);
  printf(" %i \n", -99);
  ft_printf(" %i \n", -100);
  printf(" %i \n", -100);
  ft_printf(" %i \n", -101);
  printf(" %i \n", -101);
  ft_printf(" %i \n", INT_MAX);
  printf(" %i \n", INT_MAX);
  ft_printf(" %i \n", INT_MIN);
  printf(" %i \n", INT_MIN);
  ft_printf(" %i \n", LONG_MAX);
  printf(" %i \n", LONG_MAX);
  ft_printf(" %i \n", LONG_MIN);
  printf(" %i \n", LONG_MIN);
  ft_printf(" %i \n", UINT_MAX);
  printf(" %i \n", UINT_MAX);
  ft_printf(" %i \n", ULONG_MAX);
  printf(" %i \n", ULONG_MAX);
  ft_printf(" %i \n", 9223372036854775807LL);
  printf(" %i \n", 9223372036854775807LL);
  ft_printf(" %i %i %i %i %i %i %i\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
  printf(" %i %i %i %i %i %i %i\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);

  ft_printf("THIS IS THE U TESTING FORMAT \n\n");
  ft_printf(" %u \n", 0);
  printf(" %u \n", 0);
  ft_printf(" %u \n", -1);
  printf(" %u \n", -1);
  ft_printf(" %u \n", 1);
  printf(" %u \n", 1);
  ft_printf(" %u \n", 9);
  printf(" %u \n", 9);
  ft_printf(" %u \n", 10);
  printf(" %u \n", 10);
  ft_printf(" %u \n", 11);
  printf(" %u \n", 11);
  ft_printf(" %u \n", 15);
  printf(" %u \n", 15);
  ft_printf(" %u \n", 16);
  printf(" %u \n", 16);
  ft_printf(" %u \n", 17);
  printf(" %u \n", 17);
  ft_printf(" %u \n", 99);
  printf(" %u \n", 99);
  ft_printf(" %u \n", 100);
  printf(" %u \n", 100);
  ft_printf(" %u \n", 101);
  printf(" %u \n", 101);
  ft_printf(" %u \n", -9);
  printf(" %u \n", -9);
  ft_printf(" %u \n", -10);
  printf(" %u \n", -10);
  ft_printf(" %u \n", -11);
  printf(" %u \n", -11);
  ft_printf(" %u \n", -14);
  printf(" %u \n", -14);
  ft_printf(" %u \n", -15);
  printf(" %u \n", -15);
  ft_printf(" %u \n", -16);
  printf(" %u \n", -16);
  ft_printf(" %u \n", -99);
  printf(" %u \n", -99);
  ft_printf(" %u \n", -100);
  printf(" %u \n", -100);
  ft_printf(" %u \n", -101);
  printf(" %u \n", -101);
  ft_printf(" %u \n", INT_MAX);
  printf(" %u \n", INT_MAX);
  ft_printf(" %u \n", INT_MIN);
  printf(" %u \n", INT_MIN);
  ft_printf(" %u \n", LONG_MAX);
  printf(" %u \n", LONG_MAX);
  ft_printf(" %u \n", LONG_MIN);
  printf(" %u \n", LONG_MIN);
  ft_printf(" %u \n", UINT_MAX);
  printf(" %u \n", UINT_MAX);
  ft_printf(" %u \n", ULONG_MAX);
  printf(" %u \n", ULONG_MAX);
  ft_printf(" %u \n", 9223372036854775807LL);
  printf(" %u \n", 9223372036854775807LL);
  ft_printf(" %u %u %u %u %u %u %u\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
  printf(" %u %u %u %u %u %u %u\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);

  ft_printf("THIS IS THE x TESTING FORMAT \n\n");
  ft_printf(" %x \n", 0);
  printf(" %x \n", 0);
  ft_printf(" %x \n", -1);
  printf(" %x \n", -1);
  ft_printf(" %x \n", 1);
  printf(" %x \n", 1);
  ft_printf(" %x \n", 9);
  printf(" %x \n", 9);
  ft_printf(" %x \n", 10);
  printf(" %x \n", 10);
  ft_printf(" %x \n", 11);
  printf(" %x \n", 11);
  ft_printf(" %x \n", 15);
  printf(" %x \n", 15);
  ft_printf(" %x \n", -9);
  printf(" %x \n", -9);
  ft_printf(" %x \n", -10);
  printf(" %x \n", -10);
  ft_printf(" %x \n", -11);
  printf(" %x \n", -11);
  ft_printf(" %x \n", -14);
  printf(" %x \n", -14);
  ft_printf(" %x \n", -15);
  printf(" %x \n", -15);
  ft_printf(" %x \n", -16);
  printf(" %x \n", -16);
  ft_printf(" %x \n", -99);
  printf(" %x \n", -99);
  ft_printf(" %x \n", -100);
  printf(" %x \n", -100);
  ft_printf(" %x \n", -101);
  printf(" %x \n", -101);
  ft_printf(" %x \n", INT_MAX);
  printf(" %x \n", INT_MAX);
  ft_printf(" %x \n", INT_MIN);
  printf(" %x \n", INT_MIN);
  ft_printf(" %x \n", LONG_MAX);
  printf(" %x \n", LONG_MAX);
  ft_printf(" %x \n", LONG_MIN);
  printf(" %x \n", LONG_MIN);
  ft_printf(" %x \n", UINT_MAX);
  printf(" %x \n", UINT_MAX);
  ft_printf(" %x \n", ULONG_MAX);
  printf(" %x \n", ULONG_MAX);
  ft_printf(" %x \n", 9223372036854775807LL);
  printf(" %x \n", 9223372036854775807LL);
  ft_printf(" %x %x %x %x %x %x %x\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
  printf(" %x %x %x %x %x %x %x\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
  ft_printf(" %x \n", -42);
  printf(" %x \n", -42);
  
  ft_printf("THIS IS THE X TESTING FORMAT \n\n");
  ft_printf(" %X \n", 0);
  printf(" %X \n", 0);
  ft_printf(" %X \n", -1);
  printf(" %X \n", -1);
  ft_printf(" %X \n", 1);
  printf(" %X \n", 1);
  ft_printf(" %X \n", 9);
  printf(" %X \n", 9);
  ft_printf(" %X \n", 10);
  printf(" %X \n", 10);
  ft_printf(" %X \n", 11);
  printf(" %X \n", 11);
  ft_printf(" %X \n", 15);
  printf(" %X \n", 15);
  ft_printf(" %X \n", 16);
  printf(" %X \n", 16);
  ft_printf(" %X \n", 17);
  printf(" %X \n", 17);
  ft_printf(" %X \n", 99);
  printf(" %X \n", 99);
  ft_printf(" %X \n", 100);
  printf(" %X \n", 100);
  ft_printf(" %X \n", 101);
  printf(" %X \n", 101);
  ft_printf(" %X \n", -9);
  printf(" %X \n", -9);
  ft_printf(" %X \n", -10);
  printf(" %X \n", -10);
  ft_printf(" %X \n", -11);
  printf(" %X \n", -11);
  ft_printf(" %X \n", -14);
  printf(" %X \n", -14);
  ft_printf(" %X \n", -15);
  printf(" %X \n", -15);
  ft_printf(" %X \n", -16);
  printf(" %X \n", -16);
  ft_printf(" %X \n", -99);
  printf(" %X \n", -99);
  ft_printf(" %X \n", -100);
  printf(" %X \n", -100);
  ft_printf(" %X \n", -101);
  printf(" %X \n", -101);
  ft_printf(" %X \n", INT_MAX);
  printf(" %X \n", INT_MAX);
  ft_printf(" %X \n", INT_MIN);
  printf(" %X \n", INT_MIN);
  ft_printf(" %X \n", LONG_MAX);
  printf(" %X \n", LONG_MAX);
  ft_printf(" %X \n", LONG_MIN);
  printf(" %X \n", LONG_MIN);
  ft_printf(" %X \n", UINT_MAX);
  printf(" %X \n", UINT_MAX);
  ft_printf(" %X \n", ULONG_MAX);
  printf(" %X \n", ULONG_MAX);
  ft_printf(" %X \n\n", 9223372036854775807LL);
  printf(" %X \n\n", 9223372036854775807LL);
  ft_printf(" %X %X %X %X %X %X %X\n\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
  printf(" %X %X %X %X %X %X %X\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
  ft_printf(" %X \n\n", 42);
  printf(" %X \n\n", 42);
  ft_printf(" %X \n\n", -42);
  printf(" %X \n\n", -42);

  ft_printf("THIS IS THE %% TESTING FORMAT \n\n");
  ft_printf(" %% \n");
  printf(" %% \n");
  ft_printf(" %%%% \n");
  printf(" %%%% \n\n");
  ft_printf(" %% %% %% \n");
  printf(" %% %% %% \n\n");
  ft_printf(" %%  %%  %% \n");
  printf(" %%  %%  %% \n\n");
  ft_printf(" %%   %%   %% \n");
  printf(" %%   %%   %% \n\n");
  ft_printf("%% %%\n");
  printf("%% %%\n\n");

  ft_printf("THIS IS THE MIX TESTING FORMAT \n\n");
  ft_printf("9- %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %c%% \n\n", 'A', "42\n", 42, 42 ,42 , 42, 42, 'B', "-42\n", -42, -42 ,-42 ,-42, 42, 'C', "0\n", 0, 0 ,0 ,0, 42, 0);
  printf("9- %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %c%% \n\n", 'A', "42\n", 42, 42 ,42 , 42, 42, 'B', "-42\n", -42, -42 ,-42 ,-42, 42, 'C', "0\n", 0, 0 ,0 ,0, 42, 0);

  return(0);
}
